server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: wikiClean
          uri: http://localhost:8081
          predicates:
            - Path=/wikiClean/**
        - id: reservation
          uri: http://localhost:8082
          predicates:
            - Path=/reservation/**
        - id: bookingList
          uri: http://localhost:8083
          predicates:
            - Path=/bookingList/**
        - id: pay
          uri: http://localhost:8084
          predicates:
            - Path=/pay/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: wikiClean
          uri: http://wikiClean:8080
          predicates:
            - Path=/wikiClean/**
        - id: reservation
          uri: http://reservation:8080
          predicates:
            - Path=/reservation/**
        - id: bookingList
          uri: http://bookingList:8080
          predicates:
            - Path=/bookingList/**
        - id: pay
          uri: http://pay:8080
          predicates:
            - Path=/pay/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
