apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikiClean
  labels:
    app: wikiClean
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikiClean
  template:
    metadata:
      labels:
        app: wikiClean
    spec:
      containers:
        - name: wikiClean
          image: username/wikiClean:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5